apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
  labels:
    app: iris
spec:
  replicas: 1
  selector:
      matchLabels:
        app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: xingyuusa/mlops-test:deploy_model
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: iris
spec:
  selector:
    app: iris
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30000